enableGlobalCache: true

enableImmutableInstalls: false

enableInlineBuilds: true

nodeLinker: node-modules

npmScopes:
  zuplo:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_NPM_TOKEN-remote}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
