articles:
  - title: Home
    url: /
  - title: Getting Started
    url: /quickstarts
  - title: Guides
    url: /guides
    children:
      - title: Proxy a simple GET request
        url: /guides/proxy-a-simple-get-request
      - title: Proxy a request with a body
        url: /guides/proxy-a-request-with-body
      - title: Clone a request or response
        url: /guides/safely-clone-a-request-or-response
      - title: Code Reuse
        url: /guides/reusing-code
      - title: Production Workflow
        url: /guides/production-workflow
  - title: Policies
    url: /policies
    children:
      - title: Basic Authentication
        url: /policies/basic-auth
      - title: OpenId JWT Authentication
        url: /policies/open-id-jwt
      - title: Rate Limiting
        url: /policies/rate-limiting
      - title: JSON Schema Validation
        url: /policies/json-schema-validation
  - title: Developer Portal
    url: /developer-portal
    children:
      - title: Open API
        url: /developer-portal/open-api
      - title: Documentation Portal
        url: /developer-portal/doc-portal
