articles:
  - title: Get Started
    url: /articles/getting-started
  - title: Policies
    url: /articles/policies
    children:
      - title: Basic Authentication
        url: /articles/policies/basic-auth
      - title: OpenId JWT Authentication
        url: /articles/policies/open-id-jwt
      - title: Rate Limiting
        url: /articles/policies/rate-limiting
      - title: JSON Schema Validation
        url: json-schema-validation
  - title: Reference
    url: /articles/reference
    children:
      - title: ZuploContext
        url: /articles/reference/zuplo-context
      - title: ZuploRequest
        url: /articles/reference/zuplo-request
