name: Build & Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Container Release Workflow
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_CUSTOM_TOKEN }}" \
          https://api.github.com/repos/zuplo/zuplo-docs/actions/workflows/19916176/dispatches \
          -d '{"ref":"refs/heads/main", "inputs": { "contentVersion": "${{ github.sha }}" }}'
