name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}

    permissions:
      id-token: "write"
      deployments: "write"

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/914576303414/locations/global/workloadIdentityPools/github-actions-wi-pool/providers/github-actions-wi-provider"
          service_account: "github-actions-docs@zuplo-production.iam.gserviceaccount.com"
          access_token_lifetime: "300s"

      - run: npm install
      - run: npm run ci:bundles

      - name: Upload the Worker
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: policies.v3.json
          destination: cdn.zuplo.com/portal/policies.v3.json
          headers: |-
            content-type: text/plain

      - name: Trigger Portal Release
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_CUSTOM_TOKEN }}" \
          https://api.github.com/repos/zuplo/portal/actions/workflows/25079060/dispatches \
          -d '{"ref":"refs/heads/main"}'

  search:
    name: Index Search
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v3
      - uses: darrenjennings/algolia-docsearch-action@e3b8c5540e90a964b655be6ca73c1ee1aeba2719
        with:
          algolia_application_id: E7EUGPZYED
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: crawler.json
