name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Search Index
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper
      options: -it -e "CONFIG=$(cat ./config.json | jq -r tostring)"
      env:
        APPLICATION_ID: E7EUGPZYED
        API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "DONE"
