name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Search Index
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper
      options: -it --env-file=.env -e "CONFIG=$(cat ./config.json | jq -r tostring)"
