name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}

    permissions:
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      # gsutil doesnt support workload idenity yet, when it does switch to this and delete the service account token
      # - id: "auth"
      #   name: "Authenticate to Google Cloud"
      #   uses: "google-github-actions/auth@v0"
      #   with:
      #     token_format: "access_token"
      #     workload_identity_provider: "projects/914576303414/locations/global/workloadIdentityPools/automations-pool/providers/github-provider"
      #     service_account: "github-actions@zuplo-production.iam.gserviceaccount.com"
      #     access_token_lifetime: "300s" # optional, default: '3600s' (1 hour)

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_PRODUCTION_SA }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: zuplo-production

      - run: npm install
      - run: npm run update-policies
      - run: gsutil -h "Content-Type:application/json" cp ./policies.v2.json gs://cdn.zuplo.com/portal/policies.v2.json

  search-index:
    name: Search Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@da2ed379c147b356d60dbfec68bdcfacb2791a98
        with:
          algolia_application_id: E7EUGPZYED
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: crawler.json
