name: Main
on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run format:ci
      - run: npm run lint:admonitions

  check-links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci

      - run: npm run build

      - name: Restore lychee cache
        id: cache-lychee
        uses: actions/cache/restore@v4
        with:
          path: .lycheecache
          key: lychee-cache-${{ hashFiles('.lycheecache') }}
          restore-keys: |
            lychee-cache-

      - name: Link Checker (Internal)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --fallback-extensions html --root-dir $PWD/dist --include-fragments ./dist

      - name: Link Checker (External)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --scheme https --scheme http --fallback-extensions html --root-dir $PWD/dist --include-fragments ./dist

      - name: Save lychee cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .lycheecache
          key: lychee-cache-${{ hashFiles('.lycheecache') }}

  static-assets:
    name: Upload Static Assets
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}

    permissions:
      contents: "read"
      id-token: "write"
      deployments: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/914576303414/locations/global/workloadIdentityPools/github-actions-wi-pool/providers/github-actions-wi-provider"
          service_account: "github-actions-docs@zuplo-production.iam.gserviceaccount.com"
          access_token_lifetime: "300s"

      - name: Upload Media (png)
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: dist/docs/assets/
          glob: "**/*.png"
          destination: cdn.zuplo.com/docs
          process_gcloudignore: false
          headers: |-
            cache-control: max-age=31536000
            content-type: image/png

      - name: Upload Media (gif)
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: dist/docs/assets/
          glob: "**/*.gif"
          destination: cdn.zuplo.com/docs
          process_gcloudignore: false
          headers: |-
            cache-control: max-age=31536000
            content-type: image/gif

      - name: Upload Media (svg)
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: dist/docs/assets/
          glob: "**/*.svg"
          destination: cdn.zuplo.com/docs
          process_gcloudignore: false
          headers: |-
            cache-control: max-age=31536000
            content-type: image/svg+xml
