name: Docs Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Hook
        run:
          curl -X POST
          https://api.vercel.com/v1/integrations/deploy/prj_Tb8Qh6ViE9DiS8q5CVuGaApt5f36/HoCFxKGo4K
