name: Test
on:
  deployment:
  workflow_dispatch:

jobs:
  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install --user LinkChecker
      - run:
          ~/.local/bin/linkchecker
          --ignore-url=https://docs\.zuplo\.com/.\*\(\/width\=\|/format\=\)
          https://docs.zuplo.com
